### ISSUE TITLE
New Features

### ISSUE THREAD

**Issue by mastrond** [hj91/node-red-contrib-stepper#1]
Would it be possible to be able to inject the "(From, To, Step) into the node but also do not need to have to reset it.

So basically what ever value I inject to the three fields it will just run without remembering where it left off and not having to reset the stepper.   I can't seem to find any node that does this.   I guess its possible through function node but I'm not a programmer.

**Comment by hj91** [comment]
It is possible to do so, but according to ideal control design philosophy it is always better to include an explicit reset signal from control device that is helpful in proper cycle execution

**Comment by mastrond** [comment]
Okay if it resets can we have and option to not send the payload of the from value?

**Comment by mastrond** [comment]
I am using your stepper to control a servo using the PCA9655 node.   This is perfect for controlling the speed on servos  unfortunately when I have to reset it.  it also sets the servo to the original position.   There is a work around but it gets very clumsy and adds a lot of confusion.

**Comment by hj91** [comment]
For that we need to rewrite the logic to use msg.topic functionality instead of hardcoding values in config section of node. 

Basically it is completely new development.

**Comment by mastrond** [comment]
Okay I see.  I just thought I ask if it is something that can be done easily. I will try to work it out a different way.  Thank you for your quick response and by the way I love this stepper node.

**Comment by hj91** [comment]
Maybe i can create a new node for this functionality in coming week...i will name it something different and use msg.topic feature to send values for to, from and duration variables if you need it that way.

It will be mostly same as this node but without reset functionality..

**Comment by mastrond** [comment]
That would be great.  
If that’s possible it would make things a lot easier. 
To let you inject the To, from and duration. 
maybe have it as an option inside node to have it 
Reset on its own or if people need it to remember where it stopped like you have now. 
Or if it is best to make a new node then I don’t know.  I wish my programming skills were 
not so basic or I would write some sort of code using  the function node.

**Comment by hj91** [comment]
Sure. I will check what can be done.

**Comment by hj91** [comment]
Please check this https://www.npmjs.com/package/node-red-contrib-servo
